name: Publish and commit bottles on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
jobs:
  autopublish:
    runs-on: ubuntu-22.04
    steps:
      - name: Add brew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run automerge
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: |
          sudo sed -i '/pending/d' "$(brew --repository)"/Library/Homebrew/dev-cmd/pr-automerge.rb
          brew pr-automerge --tap=${{ github.repository_owner }}/extensions --verbose --publish --without-approval --with-label=build-complete
